esphome:
  name: esphome-web-0e6a9a
  friendly_name: wattmeter

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "oZyPIeaf7yr3jnR76ybko9w1Y++FRUa+u6QIijZSv0Y="

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-0E6A9A"
    password: "7pr2W3T2lPlm"

captive_portal:
  
i2c:

  id: bus_a
  sda: GPIO0
  scl: GPIO2
  scan: true
  frequency: 100kHz

# Example configuration entry
sensor:
  - platform: ina260
    update_interval: 1s
    address: 0x40
    current:
      name: "INA260 Current"
    power:
      name: "INA260 Power"
    bus_voltage:
      name: "INA260 Bus Voltage"  