esphome:
  name: greenhouse-status-light
  friendly_name: Greenhouse Status Light

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "narI2JUCaC35wPhkuiStDC9QPuyC6RBuQOzSbowU+8c="

ota:
  password: "55748e581346c48ab8d2015b7285c596"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Greenhouse-Status-Light"
    password: "JHHNZMuWRFSJ"

captive_portal:

light:
  - platform: neopixelbus
    variant: WS2812
    pin: GPIO2
    num_leds: 4
    type: GRB
    name: "Greenhouse Status Light"
    effects:
      - addressable_scan:
          name: Scan
          move_interval: 1000ms
          scan_width: 1
      - flicker:
          name: Flicker
          alpha: 95%
          intensity: 1.5%          
      - addressable_twinkle:
          name: Twinkle
          twinkle_probability: 10%
          progress_interval: 4ms  
      - addressable_random_twinkle:
          name: Random Twinkle
          twinkle_probability: 5%
          progress_interval: 32ms                  
      - addressable_fireworks:
          name: Fireworks
          update_interval: 32ms
          spark_probability: 10%
          use_random_color: false
          fade_out_rate: 120     
      - addressable_color_wipe:
          name: Color Wipe
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 4
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 4
          add_led_interval: 100ms
          reverse: false          
      - addressable_rainbow:
          name: Rainbow
          speed: 10
          width: 50     
      - strobe:
          name: Strobe
          colors:
            - state: true
              brightness: 100%
              red: 100%
              green: 90%
              blue: 0%
              duration: 500ms
            - state: false
              duration: 250ms
            - state: true
              brightness: 100%
              red: 0%
              green: 100%
              blue: 0%
              duration: 500ms           
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%
      - pulse:
          name: "Slow Pulse"
          # transition_length: 1s      # defaults to 1s
          update_interval: 2s                       